logger:
  level: info

db_uri: mongodb://10.53.1.10/open5gs

pcf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.5:7777
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
