logger:
  level: info

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /opt/open5gs/etc/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /opt/open5gs/etc/open5gs/hnet/secp256r1-2.key
  sbi:
    server:
      - address: 10.53.1.7
        port: 7777
    client:
      nrf:
        - uri: http://10.53.1.4:7777
      scp:
        - uri: http://10.53.1.5:7777
