logger:
  level: info

upf:
  pfcp:
    server:
      - address: 10.53.1.12
    client:
      smf:
        - address: 10.53.1.3
  gtpu:
    server:
      - address: 10.53.1.12
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
